// Overview: Stores Lock Screen lifecycle commands until the React Native data provider can apply them to SQLite.

import Foundation

struct ActivityLiveActivityCommand: Codable, Hashable {
  let commandId: String
  let activityId: String
  let action: String
  let occurredAt: Int64
}

enum ActivityLiveActivityCommandStore {
  private static let appGroupIdentifier = "group.com.jas.activitytracker2"
  private static let defaultsKey = "activity-tracker.live-activity.commands"
  private static let lock = NSLock()

  // Appends a command without dropping commands generated by another Live Activity action.
  static func enqueue(activityId: String, action: String, occurredAt: Date = Date()) {
    lock.lock()
    defer { lock.unlock() }

    var commands = readCommands()
    commands.append(
      ActivityLiveActivityCommand(
        commandId: UUID().uuidString,
        activityId: activityId,
        action: action,
        occurredAt: Int64(occurredAt.timeIntervalSince1970 * 1_000),
      )
    )
    writeCommands(commands)
  }

  // Reads commands without removing them so a failed database write can be retried after foregrounding.
  static func consume() -> [ActivityLiveActivityCommand] {
    lock.lock()
    defer { lock.unlock() }
    return readCommands()
  }

  // Acknowledges only commands that the JavaScript data layer finished applying.
  static func acknowledge(commandIds: [String]) {
    guard !commandIds.isEmpty else { return }

    lock.lock()
    defer { lock.unlock() }
    let acknowledged = Set(commandIds)
    writeCommands(readCommands().filter { !acknowledged.contains($0.commandId) })
  }

  private static func readCommands() -> [ActivityLiveActivityCommand] {
    guard let data = sharedDefaults?.data(forKey: defaultsKey) else {
      return []
    }

    return (try? JSONDecoder().decode([ActivityLiveActivityCommand].self, from: data)) ?? []
  }

  private static func writeCommands(_ commands: [ActivityLiveActivityCommand]) {
    guard let data = try? JSONEncoder().encode(commands) else {
      return
    }

    sharedDefaults?.set(data, forKey: defaultsKey)
  }

  // Uses the suite shared by the app and widget extension so Lock Screen actions reach SQLite on the next app activation.
  private static var sharedDefaults: UserDefaults? {
    UserDefaults(suiteName: appGroupIdentifier)
  }
}
